config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get 'purchase_success', to: 'stripe#purchase_success'
  post 'create-checkout-session', to: 'articles#create_checkout_session'
  resources :articles
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Article < ApplicationRecord
  belongs_to :user

  has_one_attached :file, dependent: :destroy
  has_one_attached :thumbnail, dependent: :destroy do |attachable|
    attachable.variant :thumb, resize_to_limit: [200,200]
  end
end

app/models/purchase.rb
# == Schema Information
#
# Table name: purchases
#
#  id         :bigint           not null, primary key
#  status     :string
#  stripe_ref :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  article_id :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_purchases_on_article_id  (article_id)
#  index_purchases_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (article_id => articles.id)
#  fk_rails_...  (user_id => users.id)
#
class Purchase < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[ show edit update destroy create_checkout_session ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params.merge(user: current_user))

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def create_checkout_session
    session = Stripe::Checkout::Session.create({
      line_items: [{
        price: 'price_1OK0WQSElIXro00wgd4yQyLx',
        quantity: 1,
      }],
      mode: 'payment',
      success_url: "http://localhost:3000/purchase_success",
      cancel_url: article_url(@article)
    })

    redirect_to session.url, allow_other_host: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :user_id, :file, :thumbnail)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[ show edit update destroy ]

  # GET /purchases or /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1 or /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases or /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to purchase_url(@purchase), notice: "Purchase was successfully created." }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to purchase_url(@purchase), notice: "Purchase was successfully updated." }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url, notice: "Purchase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_params
      params.require(:purchase).permit(:status, :article_id, :user_id, :stripe_ref)
    end
end

app/controllers/stripe_controller.rb
class StripeController < ApplicationController
  def purchase_success
    puts params
    #session = Stripe::Checkout::Session.retrieve(params[:sesssion_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <div class="row">
    <div class="col-3">
      <% if article.thumbnail.attached? %>
        <%= image_tag article.thumbnail.variant(:thumb) %>
      <% end %>
      </div>
      <div class="col-6">
        <h3><%= article.title %></h3>
        uploaded by <%= article.user.email %>
       </div> 
       <div class="col-3">
        <%= form_with url: :create_checkout_session do |f| %>
          <%= f.hidden_field :id, value: article.id %>
          <%= f.submit "Buy Me", class: "btn btn-success" %>
        <% end %>
       </div> 
  </div>
    <p>
      <%= article.content %>
    </p>
    <div class="row">
      <% if article.file.attached? %>
        <% if article.file.video? %>
          <%= video_tag url_for(article.file), :size => "100x300", controls:"" %>
        <% elsif article.file.previewable? %>
          <div style="height:200px;width:200px">
           <%= image_tag article.file.preview(resize_to_fit: [400,400]) %>
         </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mt-2">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :thumbnail, style: "display: block" %>
    <%= form.file_field :thumbnail, class: "form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.label :file %>
    <%= form.file_field :file, class: "form-control" %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7stripedemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="/articles" class="nav-link">Articles</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 link-dark">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 link-dark">About</a></li>
        <% if current_user %>
          <li class="nav-item"><a href="#" class="nav-link px-2 link-dark"><%= current_user.email %></a></li>
        <% end %>
      </ul>
      <div class="col-md-3 text-end">
        <% if user_signed_in? %>
          <%= button_to( "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary me-2") %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-primary me-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </header>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="text-center">Rails 7 Stripe Demo</h1>
        </div>
      </div>
    <div class="row">
      <div class="col-12">
        <%= yield %>
      </div>
    <div>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :article_id, style: "display: block" %>
    <%= form.text_field :article_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :stripe_ref, style: "display: block" %>
    <%= form.text_field :stripe_ref %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>">
  <p>
    <strong>Status:</strong>
    <%= purchase.status %>
  </p>

  <p>
    <strong>Article:</strong>
    <%= purchase.article_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= purchase.user_id %>
  </p>

  <p>
    <strong>Stripe ref:</strong>
    <%= purchase.stripe_ref %>
  </p>

</div>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Purchases</h1>

<div id="purchases">
  <% @purchases.each do |purchase| %>
    <%= render purchase %>
    <p>
      <%= link_to "Show this purchase", purchase %>
    </p>
  <% end %>
</div>

<%= link_to "New purchase", new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase %>

<div>
  <%= link_to "Edit this purchase", edit_purchase_path(@purchase) %> |
  <%= link_to "Back to purchases", purchases_path %>

  <%= button_to "Destroy this purchase", @purchase, method: :delete %>
</div>

app/views/stripe/purchase_success.html.erb
<h1>Stripe#purchase_success</h1>
<p>Find me in app/views/stripe/purchase_success.html.erb</p>